name: Comment
on: pull_request
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # PRへの書き込み権限を付与する
      contents: read # permissionsを設定すると暗黙的に付与されていたcontents:readがはずれるため付与する
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # ワークフロー開始時に自動生成・終了時に破棄されるトークンを利用する

