name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
      ACTOR: ${{ github.actor }}
      HEAD_REF: ${{ github.head_ref }}
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${{ inputs.greeting }}"
      - run: echo "${ACTOR} ${HEAD_REF}"
      - run: echo "${BRANCH}"
      - run: echo "${{ format('Username:{0} Password:{1}', '${USERNAME}', '${PASSWORD}') }}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
      - run: echo "${{ toJSON(github.event) }}"
      - run: echo "${{ toJSON(github.event.*.html_url) }}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
