name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
      ACTOR: ${{ github.actor }}
      HEAD_REF: ${{ github.head_ref }}
    steps:
      - run: echo "${{ inputs.greeting }}"
      - run: echo "${ACTOR} ${HEAD_REF}"
      - run: echo "${BRANCH}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
